[#3] init
FractalFramework/oc5 pull request #16
Opened 2023-08-30 09:39 UTC by FractalFramework

service sql

2023-09-05 08:28 UTC, antoinetrouve commented on src/lib0.php
> +<?php
A quoi correspond ce fichier ?

2023-09-05 08:28 UTC, antoinetrouve commented on src/lib.php
> +
A quoi correspond ce fichier ?

2023-09-05 08:28 UTC, antoinetrouve commented on src/kernel/sql.php
> +<?php
Attention à l'indentation. Ton fichier est un peu beaucoup illisible.  Il faut mettre en place un linter pour reformatter le code.

2023-09-05 08:28 UTC, antoinetrouve commented on src/core/main.php
> +    static function call($g)
attention maintenant tu es en PHP 8.1 et tu developpes en language orienté objet (POO). donc peux tu revoir la signature de ta fonction en y indiquan tle type de retour et le type du paramètre ? Egalement, il faut proscrire les variables à une lettre qui ne veulent pas dire grand chose :)

2023-09-05 08:28 UTC, antoinetrouve commented on src/core/blocks.php
> +	static function test($p)
attention maintenant tu es en PHP 8.1 et tu developpes en language orienté objet (POO). donc peux tu revoir la signature de ta fonction en y indiquan tle type de retour et le type du paramètre ? Egalement, il faut proscrire les variables à une lettre qui ne veulent pas dire grand chose :)

2023-09-05 08:28 UTC, antoinetrouve commented on public/index.php
> +$g = gets();
Mettre des noms de variables parlant. Proscrire des noms de variables à une lettre.

2023-09-05 08:28 UTC, antoinetrouve commented on index.php
> +require('src/lib.php');
tu ne devrais avoir qu'un seul require et c'est celui de composer : 
```suggestion
require 'vendor/autoload.php';
```

et ensuite utiliser le mot clé `use`

https://www.php.net/manual/en/language.namespaces.importing.php

2023-09-05 08:28 UTC, antoinetrouve commented on .htaccess
> +RewriteRule ^$ /index.php [L]
Peux tu configurer ton git afin qu'il mette un ligne blanche par default ? 

https://docs.github.com/fr/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

2023-09-05 08:29 UTC, antoinetrouve commented on src/core/main.php
> +    static function call($g)
https://grafikart.fr/formations/programmation-objet-php

2023-09-05 08:29 UTC, antoinetrouve commented on src/core/blocks.php
> +	static function test($p)
https://grafikart.fr/formations/programmation-objet-php

2023-09-05 09:53 UTC, FractalFramework commented on src/lib0.php
> +<?php
la librairie contient les fonctions de base qui peuvent être utilisées partout de façon standard. ça évite d'avoir à répéter ces portions de code.

2023-09-05 09:54 UTC, FractalFramework commented on src/lib.php
> +
il y en a un deuxième sans indentation pour mesurer la différence de poids, qui se compte en nombre de paquets de 4ko.

2023-09-05 10:00 UTC, FractalFramework commented on src/kernel/sql.php
> +<?php
Pour moi c'est plus lisible parce que j'oublie ce que je viens de lire si je passe trop de temps à scroller pour chercher où j'en étais. C'est ça les gens qui utilisent la mémoire visuelle :)
Le kernel n'a pas à être modifié, sauf si on est prêt à impacter tout ce qui y fait appel, c'est pourquoi j'ai laissé le code compact. Mais si tu veux je vais le alt+maj+d.

2023-09-05 10:03 UTC, FractalFramework commented on src/core/main.php
> +    static function call($g)
ok pour les signatures.
mettre un classe abstraite vide ?

2023-09-05 10:09 UTC, FractalFramework commented on public/index.php
> +$g = gets();
J'utilise l'autodoc, comme en maths, les variables sont identifiées en amont.
Il y a toute une nomenclature des noms de variables, de 1 à 3 caractères, qui indiquent le type, la position ou le rôle.
Cela rend le code bien plus concis et compréhensible, si on connaît la nomenclature.
Tu vas pas être d'accord mais je préfère dix-mille fois que le code reste des maths. Le plus souvent les fonctions sont génériques, très peu sont "métier", et dans ce cas je peux m'autoriser à signaler la nature de l'objet plutôt que son type, qui du coup devient sous-entendu.

2023-09-05 10:23 UTC, FractalFramework commented on .htaccess
> +RewriteRule ^$ /index.php [L]
ah oui : git config --global core.autocrlf true

2023-09-15 07:25 UTC, antoinetrouve requested changes
Il faut désormais développer en PHP8 et programmation orientée objet. Il faut donc s'efforcer à typer les variables.

Il faut aussi mettre un declare type à chaque début de fichier php : `declare(strict_types=1);`
https://www.babeuloula.fr/blog/a-quoi-sert-declare-strict-types-1-en-php.html

2023-09-15 07:25 UTC, antoinetrouve commented on readme.md
> +## Issue 3 : sqlconnection
Ce n'est pas grand chose mais pour ce genre d'information je créerais un fichier CHANGELOG.md en spécifiant ce qui est fait.

2023-09-15 07:25 UTC, antoinetrouve commented on readme.md
> +## Travaux :
A mettre dans un CHANGELOG.md

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +    protected static $table='users';
Attention tu es POO il manque donc dans tes fonctions le type de tes paramètres et le type de retour de tes fonctions.

```suggestion
    protected static string $table='users';
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +    public $name='';
```suggestion
    public string $name='';
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +        $sql='select name from '.self::$table.' where id=?';
```suggestion
        $query = 'select name from ' . self::$table . ' where id=?';
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +        $blind=[$id];
```suggestion
        $parameters=[$id];
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +    protected static $table='users';
ca ne devrait pas être dans la classe USER. Les notions de base de données doivent être dans une classe à part. Par exemple un UserRepository dont le seul objectif de cette classe serait d'utiliser une source de données pour récupérer les informations des users ou de mettre à jour la source de données (ici la base de données).

https://www.mitrais.com/news-updates/repository-pattern-implementation-in-php/

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +        $class='\App\Controllers\User';
```suggestion
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +        return self::query($sql, $blind, $class, $one_result);
```suggestion
        return self::query($query, $parameters, User::class, $one_result);
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +
```suggestion
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +
```suggestion
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Controllers/User.php
> +}
```suggestion
}

```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Connect.php
> +    public function __construct(array $params=[])
https://stitcher.io/blog/constructor-promotion-in-php-8

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Connect.php
> +}
```suggestion
}

```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Db.php
> +    private static $params=['host'=>'localhost', 'user'=>'root', 'pass'=>'dev', 'base'=>'oc5'];
pour le moment c'est OK mais faudra trouver une autre manière de faire afin d'éviter d'avoir des informations de connexion publiées.

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Db.php
> +            self::$db=new Connect(self::$params);
```suggestion
            self::$db = new Connect(self::$params);
```

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Db.php
> +
Supprimer les lignes vides non necessaire

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Db.php
> +}
Par convention, on ajoute toujours une ligne vide à la fin de chaque fichier

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Main.php
> +class Main
idem PHP 8 et Programmation Orientée Objet

2023-09-15 07:25 UTC, antoinetrouve commented on src/Models/Main.php
> +}
idem pour la ligne en fin de fichier.

2023-09-15 07:25 UTC, antoinetrouve commented on src/public/index.php
> +require $root.'/vendor/autoload.php';
pourquoi avoir ajouter un root ?

2023-09-15 13:24 UTC, FractalFramework commented on src/public/index.php
> +require $root.'/vendor/autoload.php';
bah pourquoi pas ?

2023-09-15 13:35 UTC, FractalFramework commented on src/Controllers/User.php
> +    protected static $table='users';
Je sais mais à ce stade je réfléchis pas, je suis juste la leçon, où le gars simule ce qui est mal fait pour le refaire mieux ensuite, ce qui est assez lassant d'ailleurs. En l'occurrence cette classe est l'objet retourné par Pdo, il est donc absurde d'y loger des fonctions d'appel à Pdo...

2023-09-15 13:42 UTC, FractalFramework commented on src/Models/Connect.php
> +    public function __construct(array $params=[])
ooh

2023-09-15 14:03 UTC, FractalFramework commented on src/Controllers/User.php
> +    protected static $table='users';
et pourquoi pas plutôt mettre dans un dossier spécifique les classes vont utiliser Pdo, qui sont appellées par le getter, et laisser ça là, dans son dossier "controller", puisque c'est ce que ça fait ?

2023-09-20 09:51 UTC, merged